server:
  port: 7901

spring:
  application:
    name: microservice-consumer-movie-feign-customizing-without-hystrix

eureka:
  client:
  #健康检查
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  # 服务实例信息显示配置
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}

# 日志配置
logging:
  level:
    # 开启指定feignclient的配置
    com.aws.springcloud.movie.client.UserFeignClient: DEBUG

#开启feign的熔断机制，否则fallback无效（此处是个坑，看文档，看文档，看文档）
feign:
  hystrix:
    enabled: true