server:
  port: 8010

spring:
  application:
    name: microservice-consumer-movie-ribbon-without-eureka

eureka:
  client:
  #健康检查
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
#    enabled: false
  # 服务实例信息显示配置
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}

# 除去eureka
ribbon:
  eureka:
   enabled: false

# 配置服务列表
microservice-provider-user:
  ribbon:
    listOfServers: localhost:7900,localhost:7901