server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:806737859/config-repo.git
  security: # 跟eurekaServer配置一样，访问这个ConfigServer需要验证
    user:
      name: user
      password: password123