server:
  port: 7901

spring:
  application:
    name:

eureka:
  client:
  #健康检查
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  # 服务实例信息显示配置
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}

    # 配置元信息
#    metadata-map:
#      key: value
