server:
  port: 8080

spring:
  application:
      name: microservice-config-server-with-eureka
  cloud:
    config:
      server:
        git:
          uri: git@github.com:806737859/config-repo.git

# 将ConfigServer注册到eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    #以ip地址注册到eureka，默认是主机名
    prefer-ip-address: true

#使用场景：这种方式适用于ConfigServer高可用的情况