server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka

# hystrix集群监控
turbine:
  aggregator:
    clusterConfig: default  #聚合那些集群，默认为default，多个用“,”分割，可以使用http://.../turbine.stream?cluster={clusterConfig}访问
  appConfig: microservice-consumer-movie-ribbon-with-hystrix,microservice-consumer-movie-feign-with-hystrix # 配置eureka中的serviceId列表，表明监控那些服务
  cluster-name-expression: "'default'"
  #1. cluster-name-expression指定集群名称，默认表达式appName；此时：turbine.aggregator.clusterConfig需要配置想要监控的应用名称
  #2. 当cluster-name-expression:default时，turbine.aggregator.clusterConfig可以不写，因为默认就是default
  #3. 当cluster-name-expression:metadata['cluster']时，假设想要监控的应用配置是eureka.instance.metadata-map: ABC，则需要配置，同时turbine.aggregator.clusterConfig: ABC

# 开启turbine监控日志
#logging:
#  level:
#    root: INFO
#    com.netflix.turbine.monitor: DEBUG