server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

#配置路由
zuul:
  routes:
    xxx: #路由id
      path: /user/**
      serviceId: microservice-provider-user

# /actuator/routes{/details} 查看服务路由url映射
# /actuator/filters 查看所有的过滤器
management:
  #端口管理，默认只开启 health 和 info端口
  endpoints:
    web:
      exposure:
        # 过滤的端口，优先级高于include
        exclude: env,beans
        # 开放的端口
        include: "*"

logging:
  level:
    com.netflix: debug

