server:
  port: 8041
spring:
  application:
    name: microservice-gateway-zuul-regular-expression
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
