server:
  port: 8080

# 使用这种方式，可以实现每个微服务对应一个git仓库，有良好的隔离性
# 其中{application}就是一个占位符，对应需要使用配置中心的微服务的spring.application.name
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/806737859/springcloud-demo/tree/master/springcloud-config/springcloud-config
#          uri: https://github.com/806737859/springcloud-demo/springcloud-config/springcloud-config
#          uri: git@github.com:806737859/{application}  # ConfigServer后端存储url，及配置中心的git地址

#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: git@github.com:806737859/config-repo.git    # 默认的配置中心的git仓库
#          repos:
#            simple: git@github.com:806737859/simple        # 只匹配spring.application.name=simple的微服务
#            special:
#              pattern: special*/dev*,*special*/dev*        
#              uri: git@github.com:806737859/special
#            local:
#              pattern: local*
#              uri: file:/home/configsvc/config-repo