server:
  port: 7901

spring:
  application:
    name: microservice-consumer-movie-feign

eureka:
  client:
    #如果配置该参数，会优先访问相同zone的服务，但是该zone的服务down了，也会调用失败
    #此时可以开启ribbon的重试机制
    preferSameZoneEureka: true
    #健康检查
    healthcheck:
      enabled: true
      #注册到eureka 方式一
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/ # http://user:password123@localhost:8761/eureka
  # 服务实例信息显示配置
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
      #注册到eureka 方式二
#    metadata-map:
#      zone: http://peer1:8761/eureka/
